### PR TITLE
Feat: lesson9

### PR DESCRIPTION
**Pull request by yuka830**
# [Lesson9](https://github.com/kenmori/handsonFrontend/blob/master/work/markup/1.md#9)
## [CodeSandbox](https://codesandbox.io/s/lesson9-m49wd?file=/main.js)
Last commit [608038a](https://github.com/yuka830/js-lessons/pull/11/commits/608038a65cb4be77574038de7cdfdf30d1373121)
Rewriting the then method with async/await.

[Question]
I'm a little worry about some constant name are appropriate.(`callList` and `listsContents`)

### CODE REVIEW

**Comment by ghost** [comment]
> [Question]
I'm a little worry about some constant name are appropriate.(callList and listsContents)

I thought they were appropriate.
I approve.

**Review by ghost — APPROVED** [review]

**Review by matsuwork — APPROVED** [review]

**Comment by rik9228** [comment]
```
const wrapper = document.getElementById("js-wrapper");
const ul = document.getElementById("js-lists");
const fragment = document.createDocumentFragment();
```

Do these need to be defined globally?
It seems to me that they are limited to the areas where they are used.

**Comment by rik9228** [comment]
```
const wrapper = document.getElementById("js-wrapper");
const ul = document.getElementById("js-lists");
const fragment = document.createDocumentFragment();
```

nits:
Sorry, I should have mentioned this before.
Do these need to be defined globally?
I have a feeling that its use is limited.

**Comment by yuka830** [comment]
@rik9228 
Thank you for the comments :)
Is this interpretation correct? If I'm wrong, please kindly teach me.

1. Move `const wrapper` into the `const loading`
2. Move `const ul` and `const fragment` into the `const createNewList` 

[CodeSandbox](https://codesandbox.io/s/lesson9-m49wd?file=/main.js)
I changed only CodeSandbox.

**Comment by rik9228** [comment]
> @rik9228
> Thank you for the comments :)
> Is this interpretation correct? If I'm wrong, please kindly teach me.
> 
> 1. Move `const wrapper` into the `const loading`
> 2. Move `const ul` and `const fragment` into the `const createNewList`
> 
> [CodeSandbox](https://codesandbox.io/s/lesson9-m49wd?file=/main.js)
> I changed only CodeSandbox.

Yes. This is what I assumed！

**Comment by yuka830** [comment]
@rik9228
I've changed them. Thank you for teaching!
[608038a](https://github.com/yuka830/js-lessons/pull/11/commits/608038a65cb4be77574038de7cdfdf30d1373121)

**Pull request merged**
